kind: Deployment
apiVersion: apps/v1
metadata:
  name: tetris
  labels:
    app: tetris
    app.kubernetes.io/component: tetris
    app.kubernetes.io/instance: tetris
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: tetris
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: tetris
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: tetris
          image: REPLACE_IMAGE
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
